### ISSUE TITLE
unexpected "export"

### ISSUE THREAD

**Issue by amlcodes** [scaffold-eth/eth-hooks#86]
using with nextjs typescript, when importing any hook from the library, throws error when reading "export * from './useBlockNumber'; at index.js. 

Is the best way to contribute here adding a github action that publishes a package to npm on successful push or pr to main that works with the tests and this scenario?

**Comment by ShravanSunder** [comment]
which version are you using? v2 or v3?  I'm assuming you're working with v2.  I'm not sure I understand your question, so could you expand on that?  @amlcodes 

- #66 is about publishing an npm package when there is a new merge to master

**Comment by ShravanSunder** [comment]
closed because lack of info

**Comment by dellwatson** [comment]
@ShravanSunder  it is on version v2 --> "2.3.8"

It seems every new version removed the old one? 
I'm on version v2 because using `import { useExchangeEthPrice } from "eth-hooks/dapps/dex";` can give me error on v4.
but now it encounters this problem `export` things

it's hard to debug because Idk where is the old docs, and I'm not sure how to contribute this eth-hooks docs, please let me know because I have fresh knowledge about this. So I know what's good to add in the docs for new people too

**Comment by dellwatson** [comment]
seems typescript issue?
https://github.com/scaffold-eth/scaffold-eth/pull/434

i also use nextjs + ts, and moving some codes from scaffold-eth with nextjs branch

**Comment by ShravanSunder** [comment]
v2 is used by `scaffold-eth` but not `scaffold-eth-typescript` (which uses v4).  v4 has different export locations
